### ISSUE TITLE
Create Feature Request issue at 'deck.gl' - TileLayer improvements

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/deck.gl#11]
We're gonna create a 'Feature' issue upstream, to start a technical conversation and to validate that our current approach could work (and offer some interesting improvements to the library)

**Comment by VictorVelarde** [comment]
This is their current template:

#### Target Use case


#### Proposed feature


#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by VictorVelarde** [comment]
## TileLayer performance improvement

#### Target Use case
We have started to test TileLayer for dealing with MVT Tiles. Working to improve its performance would be relevant for this and probably more use cases.

#### Proposed feature
We have checked (using an approach as described in [TileLayer](https://github.com/uber/deck.gl/blob/master/docs/layers/tile-layer.md)) that the major performance cost is applying a `renderSubLayers` call per tile. 

What we propose here, as a first step, is trying to manage the Tiles differently (per z level), reducing the number of render calls.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by VictorVelarde** [comment]
Please @jesusbotella check this 🔝 , so we can open an Issue

**Comment by jesusbotella** [comment]
That's what we'd be posting in the issue/feature request, right?

**Comment by VictorVelarde** [comment]
Yeah. That's it. Then we could start a technical dialog with them

**Comment by jesusbotella** [comment]
Looks good to me! It's enough to kickstart the conversation, and then let them know about our improvements later.

**Comment by VictorVelarde** [comment]
>> Issue & more conversation moved to issue 3695 upstream
